=== runtipi/runtipi-appstore/apps/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "available": {
      "type": "boolean"
    },
    "deprecated": {
      "type": "boolean"
    },
    "exposable": {
      "type": "boolean"
    },
    "no_gui": {
      "type": "boolean"
    },
    "port": {
      "type": "integer",
      "minimum": 0,
      "maximum": 65535
    },
    "https": {
      "type": "boolean"
    },
    "uid": {
      "type": "integer"
    },
    "gid": {
      "type": "integer"
    },
    "force_expose": {
      "type": "boolean"
    },
    "generate_vapid_keys": {
      "type": "boolean"
    },
    "requirements": {
      "type": "object",
      "properties": {
        "ports": {
          "type": "array",
          "items": [
            {
              "type": "integer"
            }
          ]
        }
      }
    },
    "supported_architectures": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "id": {
      "type": "string",
      "pattern": "^[a-z0-9-_]+$"
    },
    "tipi_version": {
      "type": "integer"
    },
    "version": {
      "type": "string"
    },
    "categories": {
      "type": "array",
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    },
    "description": {
      "type": "string"
    },
    "short_desc": {
      "type": "string"
    },
    "author": {
      "type": "string"
    },
    "source": {
      "type": "string",
      "format": "uri"
    },
    "website": {
      "type": "string",
      "format": "uri"
    },
    "url_suffix": {
      "type": "string",
      "pattern": "^/[a-z0-9-_/]+$"
    },
    "form_fields": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "type": {
              "type": "string"
            },
            "label": {
              "type": "string"
            },
            "max": {
              "type": "integer"
            },
            "min": {
              "type": "integer"
            },
            "required": {
              "type": "boolean"
            },
            "env_variable": {
              "type": "string"
            }
          },
          "required": [
            "type",
            "label",
            "env_variable"
          ]
        }
      ]
    },
    "dynamic_config": {
      "type": "boolean"
    },
    "created_at": {
      "type": "number"
    },
    "updated_at": {
      "type": "number"
    }
  },
  "required": [
    "name",
    "available",
    "port",
    "id",
    "tipi_version",
    "version",
    "categories",
    "description",
    "short_desc",
    "author",
    "source",
    "form_fields"
  ]
}

=== runtipi/runtipi-appstore/apps/arkanum-fh/config.json
{
  "id": "arkanum-fh",
  "available": true,
  "port": 8153,
  "name": "Arkanum-FH",
  "description": "An opinionated VS Code distribution. Start coding remotely with a containerized editor.",
  "version": "1.8.3",
  "tipi_version": 2,
  "short_desc": "An opinionated VS Code distribution.",
  "author": "OCram85",
  "source": "https://gitea.ocram85.com/arkanum/arkanum",
  "website": "https://arkanum.dev/",
  "categories": ["development"],
  "form_fields": [
    {
      "type": "password",
      "label": "Password",
      "max": 50,
      "min": 8,
      "required": false,
      "hint": "Optional web gui password, if Password or Hashed Password is not provided, there will be no auth.",
      "env_variable": "ARKANUM_PASSWORD"
    },
    {
      "type": "text",
      "label": "Hashed Password",
      "required": false,
      "hint": "Optional web gui password, overrides Password, instructions on how to create in the App description.",
      "env_variable": "ARKANUM_HASHED_PASSWORD"
    },
    {
      "type": "password",
      "label": "Sudo Password",
      "max": 50,
      "min": 8,
      "required": false,
      "hint": "If this optional variable is set, user will have sudo access in the Arkanum terminal with the specified password.",
      "env_variable": "ARKANUM_SUDO_PASSWORD"
    },
    {
      "type": "password",
      "label": "Sudo Password Hash",
      "max": 50,
      "min": 8,
      "required": false,
      "hint": "Optionally set sudo password via hash (takes priority over SUDO_PASSWORD var). Format is $type$salt$hashed.",
      "env_variable": "ARKANUM_SUDO_PASSWORD_HASH"
    },
    {
      "type": "text",
      "label": "Default Workspace",
      "required": false,
      "placeholder": "/config/workspace",
      "default": "/config/workspace",
      "hint": "If this optional variable is set, code-server will open this directory by default (defaults to: /config/workspace)",
      "env_variable": "ARKANUM_DEFAULT_WORKSPACE"
    }
  ],
  "https": true,
  "exposable": true,
  "supported_architectures": ["arm64", "amd64"],
  "dynamic_config": true,
  "created_at": 1737116464890,
  "updated_at": 1737116464890,
  "$schema": "../app-info-schema.json"
}

=== runtipi/runtipi-appstore/apps/n8n-1/config.json
{
  "$schema": "../app-info-schema.json",
  "name": "n8n",
  "available": true,
  "exposable": true,
  "dynamic_config": true,
  "port": 8215,
  "id": "n8n-1",
  "tipi_version": 11,
  "version": "1.87.2",
  "categories": ["automation"],
  "description": "n8n is an extendable workflow automation tool. With a fair-code distribution model, n8n will always have visible source code, be available to self-host, and allow you to add your own custom functions, logic and apps. n8n's node-based approach makes it highly versatile, enabling you to connect anything to everything.",
  "short_desc": "Workflow Automation Tool. Alternative to Zapier",
  "author": "n8n.io",
  "source": "https://github.com/n8n-io/n8n",
  "website": "https://n8n.io/",
  "form_fields": [
    {
      "type": "random",
      "label": "Database Password",
      "min": 32,
      "env_variable": "N8N_DB_PASSWORD"
    },
    {
      "type": "random",
      "label": "Database Non Root Password",
      "min": 32,
      "env_variable": "N8N_NR_DB_PASSWORD"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1744219074000
}

=== runtipi/runtipi-appstore/apps/guacamole/config.json
{
  "$schema": "../schema.json",
  "name": "Guacamole",
  "id": "guacamole",
  "available": true,
  "short_desc": "Clientless remote desktop gateway",
  "author": "apache",
  "port": 8854,
  "url_suffix": "/guacamole",
  "categories": ["utilities"],
  "description": "Apache Guacamole is a clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH",
  "tipi_version": 1,
  "version": "1.5.5",
  "source": "https://github.com/apache/guacamole-server",
  "website": "https://guacamole.apache.org",
  "exposable": true,
  "supported_architectures": ["amd64"],
  "form_fields": [
    {
      "type": "random",
      "min": 32,
      "label": "Guacamole postgres password",
      "env_variable": "GUACAMOLE_DB_PASSWORD"
    }
  ],
  "created_at": 1691943801422,
  "updated_at": 1723566283000
}

=== runtipi/runtipi-appstore/apps/sonarr-french/config.json
{
  "$schema": "../schema.json",
  "name": "SonarrFr",
  "available": true,
  "exposable": true,
  "port": 8099,
  "id": "sonarrfr",
  "tipi_version": 7,
  "version": "4.0.1",
  "categories": [
    "media",
    "utilities"
  ],
  "description": "Sonarr is a PVR for Usenet and BitTorrent users. It can monitor multiple RSS feeds for new episodes of your favorite shows and will grab, sort and rename them. It can also be configured to automatically upgrade the quality of files already downloaded when a better quality format becomes available.",
  "short_desc": "TV show manager for Usenet and BitTorrent",
  "author": "sonarr.tv",
  "source": "https://github.com/Sonarr/Sonarr",
  "form_fields": [],
  "supported_architectures": ["arm64", "amd64"]
}

=== runtipi/runtipi-appstore/apps/linkstack/config.json
{
  "$schema": "../app-info-schema.json",
  "name": "LinkStack",
  "port": 8154,
  "available": true,
  "exposable": true,
  "dynamic_config": true,
  "id": "linkstack",
  "tipi_version": 3,
  "version": "latest",
  "categories": ["media"],
  "description": "LinkStack is a highly customizable link sharing platform with an intuitive, easy to use user interface",
  "short_desc": "LinkStack is a highly customizable link sharing platform with an intuitive, easy to use user interface",
  "author": "LinkStackOrg",
  "source": "https://github.com/LinkStackOrg/linkstack-docker",
  "form_fields": [
    {
      "type": "email",
      "label": "Admin email",
      "max": 50,
      "min": 3,
      "required": true,
      "env_variable": "LINKSTACK_CUSTOM_EMAIL"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1738177482197
}

=== runtipi/runtipi-appstore/apps/homeassistant/config.json
{
  "$schema": "../schema.json",
  "name": "Home Assistant non exposed",
  "available": true,
  "deprecated": true,
  "port": 8123,
  "tipi_version": 3,
  "version": "stable",
  "id": "homeassistant",
  "categories": ["automation"],
  "description": "Open source home automation that puts local control and privacy first. Powered by a worldwide community of tinkerers and DIY enthusiasts. Perfect to run on a Raspberry Pi or a local server.",
  "short_desc": "Open source home automation that puts local control and privacy first",
  "author": "ArneNaessens",
  "source": "https://github.com/home-assistant/core",
  "form_fields": [],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1723566283000
}

=== runtipi/runtipi-appstore/apps/kasm-workspaces/config.json
{
  "name": "Kasm Workspaces",
  "available": true,
  "port": 8744,
  "exposable": false,
  "dynamic_config": true,
  "id": "kasm-workspaces",
  "description": "Kasm Workspaces is a docker container streaming platform for delivering browser-based access to desktops, applications, and web services.",
  "tipi_version": 4,
  "version": "1.120.20221218",
  "categories": ["utilities"],
  "short_desc": "Container streaming platform.",
  "author": "Kasm",
  "source": "https://github.com/kasmtech",
  "website": "https://www.kasmweb.com/",
  "form_fields": [],
  "supported_architectures": ["arm64", "amd64"],
  "https": true,
  "created_at": 1691943801422,
  "updated_at": 1738177463033,
  "$schema": "../app-info-schema.json"
}

=== runtipi/runtipi-appstore/apps/eclipse-mosquitto/config.json
{
  "$schema": "../schema.json",
  "name": "Eclipse Mosquitto",
  "port": 8288,
  "available": true,
  "exposable": true,
  "id": "eclipse-mosquitto",
  "tipi_version": 1,
  "version": "2.0.18",
  "categories": ["utilities", "automation"],
  "description": "Eclipse Mosquitto is an open source message broker that implements the MQTT protocol.",
  "short_desc": "The MQTT protocol provides a lightweight method of carrying out messaging using a publish/subscribe model.",
  "author": "Eclipse Foundation",
  "source": "https://github.com/eclipse/mosquitto/",
  "website": "https://mosquitto.org/",
  "form_fields": [
    {
      "type": "password",
      "label": "MQTT Broker Admin Password",
      "max": 50,
      "min": 6,
      "required": true,
      "env_variable": "MQTT_ADMIN_PASSWORD"
    },
    {
      "type": "password",
      "label": "Cedalo Management Center Password",
      "max": 50,
      "min": 6,
      "required": true,
      "env_variable": "CEDALO_MC_PASSWORD"
    }
  ],
  "supported_architectures": ["arm64", "amd64"],
  "created_at": 1691943801422,
  "updated_at": 1723566283000
}
